version: "3"
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mysql
    container_name: dullahan-mysql-db
    ports:
      - "3312:3306"
    environment:
      # for root user. other users are created in provision script
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maindb
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
