version: "3"
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.postgres
    container_name: dullahan-postgresql-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-maindb}
      # Superuser creds, should be used by DBA only
      # Application users are created in provision script
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
